### ISSUE TITLE
Migrate Sample code to the acs-aem-samples repository

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/acs-aem-samples#1]
Fork: https://github.com/davidjgonzalez/acs-aem-samples (master)

Then copy/paste Samples from:  https://github.com/activecq/com.activecq.samples/tree/master/core/src/main/java/com/activecq/samples into the acs-aem-samples project.

Migration activities: 
- Changing package naming to be “com.adobe.acs.samples”
- Update any @Component labels to be “ACS AEM Samples - <Sample Name>”
- Code review/cleanup — worth sanity checking them; I wrote these years ago
- Clarify any code w comments
- Break up samples that are tackle too many “topics”
- Generally the samples should do almost no “business” work; any “work” done should be very simple and straight foward. These samples are currently less about how to execute business functionality, but rather how/when/why to leverage the various building blocks in AEM..

Before "migrating" a sample, add it to this comment (and ensure someone else hasn't already claimed the sample for migration)
## Migrated Samples
- SampleAdapterFactory.java
- SampleSlingIncludeFilter.java
- SampleSlingRequestFilter.java
- SampleThreadLocalFilter.java
- SampleServiceImpl.java
- SampleJsonHitWriter.java
- SampleMultiReferenceServiceImpl.java
- SampleMutableStateServiceImpl.java
- SampleServiceImpl.java
- SampleAllMethodsServlet.java
- SampleSafeMethodsServlet.java
- SampleMBeanImpl.java
- SampleScheduledService.java
- SampleSlingResourceProvider.java
- workflow/\* (@kalyanar - in process)
- clientcontext/\* (@kalyanar - in process)

**Comment by kalyanar** [comment]
I have taken this up.

**Comment by davidjgonzalez** [comment]
@kalyanar thanks! It's really appreciated!
A few other folks have expressed interest as well; if you just add which sample you're working to this issue (just post a comment) then we can easily ensure there isn't overlap -- before picking a new sample to migrate just make sure someone else hasn't "claimed" it. I think there are plenty to go around.

**Comment by kalyanar** [comment]
I have converted taken up the workflow and clientcontext packages.
the pom is for 5.6.1 i think. Should we create samples for 6.0 only?
Also , I am changing all repo.loginAdministrative to a service user for 6.0 version

**Comment by kalyanar** [comment]
@davidjgonzalez how about resource merger, virtual components etc.,?

**Comment by davidjgonzalez** [comment]
@kalyanar We should focus on AEM6; if there are samples that are 5.x that might be useful (example - the existing Auth Handlers), we can put them in a "cq5" package .. like `com.adobe.acs.samples.authenticationhandlers.cq5.impl` ... WDYT?

Wrt to ResourceMerger and Virtual Components; definitely!! Sounds great - currently the `content` proj is empty but feel free to add to it.

**Comment by davidjgonzalez** [comment]
Grabbing Mbeans

**Comment by davidjgonzalez** [comment]
Grabbing Sling Resource Provider

**Comment by davidjgonzalez** [comment]
@kalyanar FYI - updated the POM's to include AEM6 deps (used the ACS Lazybones AEM6 settings). These are in my Fork right now.

**Comment by davidjgonzalez** [comment]
@kalyanar I think we almost have enough moved over to push to the ACS's acs-aem-samples repo; looking through some of the other samples in my source repo; i think they warrant re-writing rather than just migrating over -- they feel either too specific, or not well explained. WDYT?

/cc @justinedelson

**Comment by davidjgonzalez** [comment]
@kalyanar @justinedelson  FYI - pushed this live tonight! http://adobe-consulting-services.github.io/acs-aem-samples/

Thanks for the help @kalyanar !
