### ISSUE TITLE
SampleJsonHitWriter should use hit.getProperties()

### ISSUE THREAD

**Issue by alexkli** [Adobe-Consulting-Services/acs-aem-samples#20]
[SampleJsonHitWriter.java](https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/querybuilder/impl/SampleJsonHitWriter.java) currently does

``` java
final Resource resource = hit.getResource();
final ValueMap properties = resource.adaptTo(ValueMap.class);
```

but it could use `hit.getProperties()` right away, see [the javadocs](http://docs.adobe.com/docs/en/cq/current/javadoc/com/day/cq/search/result/Hit.html#getProperties%28%29).

This also handles the common `jcr:content` nodes and will return a ValueMap based on the jcr:content node, if present.

Hence line 84/85 can be changed from:

``` java
jsonWriter.key("key-to-use-in-json").value(properties.get("jcr:content/jcr:title",
                "") + "(pulled from jcr:content node)");
```

to

``` java
jsonWriter.key("key-to-use-in-json").value(hit.getProperties().get("jcr:title", "") + "(pulled from jcr:content node)");
```

**Comment by davidjgonzalez** [comment]
Thanks @alexkli - thanks for the input! Made a slight adjustment to facilitate the commenting narrative.
