### ISSUE TITLE
Cannot build and deploy with Maven 3.3.3

### ISSUE THREAD

**Issue by schumacher-cgn** [Adobe-Consulting-Services/acs-aem-samples#33]
Running the Maven command with Maven Version 3.3.3
mvn clean install -PautoInstallBundle

results into the following error:
[ERROR] Failed to execute goal com.day.jcr.vault:content-package-maven-plugin:0.
0.23:package (default-package) on project acs-aem-samples-content: Execution def
ault-package of goal com.day.jcr.vault:content-package-maven-plugin:0.0.23:packa
ge failed: A required class was missing while executing com.day.jcr.vault:conten
t-package-maven-plugin:0.0.23:package: org/slf4j/helpers/MarkerIgnoringBase

When switching to Maven 3.0.5 everything is fine and the package is being deployed.
Is this a Maven issue or an issue here?

**Comment by khakiout** [comment]
@mschumac I believe this is a Maven issue (see: [MNG-5787](https://issues.apache.org/jira/browse/MNG-5787))

**Comment by justinedelson** [comment]
Can be fixed by upgrading to content-package-maven-plugin 0.0.24.
