### ISSUE TITLE
com.adobe.acs.samples.querybuilder.facets.SampleSearch and SampleSearchClient missing

### ISSUE THREAD

**Issue by hellonitin** [Adobe-Consulting-Services/acs-aem-samples#35]
Unable to compile the code as i could not find the classes com.adobe.acs.samples.querybuilder.facets.SampleSearch and SampleSearchClient which are used in SampleFacetPredicateClientImpl .

Where could i find these classes .

**Comment by davidjgonzalez** [comment]
@kaushnitin It should just be SampleSearchClient, and it is just a simple interface to allow the Impl to be called if you like .. 

Updated now:
https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/querybuilder/facets/impl/README.md
