### ISSUE TITLE
Possible to extend the side bar?

### ISSUE THREAD

**Issue by davidknezic** [Adobe-Consulting-Services/acs-aem-samples#41]
Is it possible to add a new customized section to the side panel when authoring a page? We'd love to integrate our enterprise asset management into the workflow of our editors.

![image](https://cloud.githubusercontent.com/assets/198988/12511727/dcf583ca-c113-11e5-9365-ddfce25f91e5.png)

**Comment by davidjgonzalez** [comment]
@davidknezic see is @schoudry covers this on his blog ... http://experience-aem.blogspot.com/2013/08/in-blog-experiencing-adobe-experience.html

**Comment by davidknezic** [comment]
Thx @davidjgonzalez. This blog is one big treasure trove!
However, while I found an example adding a new panel to the classic sidekick, there's none extending the Touch UI sidepanel. @schoudry?

**Comment by schoudry** [comment]
@davidknezic sorry I dont think there is one in the blog

**Comment by davidjgonzalez** [comment]
Checkout... https://github.com/Adobe-Marketing-Cloud/aem-authoring-extension-assetfinder-flickr

Would be awesome if you could pr back a sample at the end!

**Comment by davidknezic** [comment]
:+1: When I find out, I'll absolutely make a pr!

**Comment by schoudry** [comment]
@davidknezic check this post http://experience-aem.blogspot.com/2016/01/aem-61-touchui-extending-side-panel-for-adding-tab-page-tree.html

just for kicks added the classic page tree in new tab

![image](https://cloud.githubusercontent.com/assets/6585493/12624994/647878c0-c4f7-11e5-87a3-1aec1ab8403a.png)

**Comment by davidknezic** [comment]
Amazing!!

``` js
var $sidePanelEdit = $("#SidePanel").find(".js-sidePanel-edit"),
    $tabs = $sidePanelEdit.data("tabs");

//add the page itree iframe in new tab
$tabs.addItem({
  tabContent: "Page Browser",
  panelContent: getPageContent(),
  active: false
});
```

That's exactly it! Thank you so much @schoudry for writing this!
