### ISSUE TITLE
Angular2 RuntimeCompiler issue with Adobe AEM

### ISSUE THREAD

**Issue by vasuneet** [Adobe-Consulting-Services/acs-aem-samples#52]
Hi I have the AEM integration issue with our angular2 code. We want to use templates from Adobe AEM and those templates need to be binded with Angular2 component. So there is a need for RuntimeCompiler. With AOT it is not working but without AOT we are able to use Adobe AEM template in our Angular2 Components and compile it dynamically. please let us know how we can do that ?

**Comment by ireasor** [comment]
The Angular Sample app here is built using Angular 1.x.  In Angular 1.x, you could simply add directives to your existing HTML, which made it straightforward to integrate with AEM.  Angular 2 takes a very different approach to how it handles your HTML, expecting it to be in Angular components and injected through AJAX, which makes authoring difficult.

I have yet to see a way to integrate Angular 2 while still retaining AEM's rich authoring experience and have not been recommending it as a result of that.  If you find a way to do this, I'd be interested in seeing your approach.

In any case, this isn't intended to be a support forum, so I'm going to close this issue.  You should try posting at http://help-forums.adobe.com/content/adobeforums/en/experience-manager-forum/adobe-experience-manager.html to see if others have ideas.
