### ISSUE TITLE
com.adobe.acs.samples.events.impl.SampleJcrEventListener should not be a @Service

### ISSUE THREAD

**Issue by justinedelson** [Adobe-Consulting-Services/acs-aem-samples#53]
AFAICT, there's no reason for com.adobe.acs.samples.events.impl.SampleJcrEventListener to be an `@Service`. JCR EventListeners are not registered through the OSGi service registry and this class doesn't implement any other service interfaces.

Should probably remove this annotation and also the `immediate=true` attribute from the `@Component` annotation (since components which aren't services are automatically immediate).

**Comment by davidjgonzalez** [comment]
Fixed via 761ee9fd3f44cb59bdc70f754c4486e9ca2f9e0d
