### ISSUE TITLE
Null pointer exception in SlingRequestFilter when working with launches in AEM 6.2

### ISSUE THREAD

**Issue by zahidmak** [Adobe-Consulting-Services/acs-aem-samples#58]
Hello,

I have implemented SlingRequestFilter for restricted DAM access. However, launches functionality in AEM has stopped working because of null pointer exception thrown at below line in bold. Could you please advise how I can resolve this or what possible scenario is throwing this exception.

    _// Forcing false in this sample so else this will break AEM when installed
    if (false && response.getContentType().contains("html")) {
        // In this example, checking for html response type since the comments are HTML format and would break
        // binary, json, etc. responses

        // Write some more content to the response before this chain has executed
        //response.getWriter().write("");

        // Proceed with the rest of the Filter chain
        chain.doFilter(request, response);

        // Write some more content to the response after this chain has executed
        //response.getWriter().write("");
    }  else {
        **chain.doFilter(request, response);**
    }
}_

Log file attached.

[error.txt](https://github.com/Adobe-Consulting-Services/acs-aem-samples/files/1041541/error.txt)

Thank you,

**Comment by davidjgonzalez** [comment]
@zahidmak the NPE is thrown well after the bolded line is called (chain.doFilter(request, response)) ... so i dont think this has anything to do w the Filter (since it appears all you do it pass it through anyhow without changing anything about the request or response.
