### ISSUE TITLE
Felix filter execution order issue in AEM 6.2

### ISSUE THREAD

**Issue by sandeepkumar03** [Adobe-Consulting-Services/acs-aem-samples#63]
We have a felix filter handling the custom authentication in 6.1 similar to [this acs aem sample filter](https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/filters/impl/SampleServletFilter.java). As per specification, Felix filter should get executed before Sling Engine. Thats happening in AEM 6.1 but NOT in AEM 6.2.

**Steps to reproduce**

1. Deploy OSGi bundle with Sample Filter to AEM 6.1, 6.2
2. Hit URL in new browser session
3. Observe execution order in 6.1 (Filter -> Sling Authentication)
```
04.01.2018 11:31:44.131 *INFO* [qtp1030969174-68] com.sample.project.core.filters.SampleServletFilter Calling Sample Servlet Filter
04.01.2018 11:31:44.132 *INFO* [qtp1030969174-68] org.apache.sling.auth.core.impl.SlingAuthenticator getAnonymousResolver: Anonymous access not allowed by configuration - requesting credentials
```
4. Observe execution order in 6.2 (Sling Authentication -> Filter)
```
04.01.2018 11:26:33.364 *INFO* [qtp774039123-271] org.apache.sling.auth.core.impl.SlingAuthenticator getAnonymousResolver: Anonymous access not allowed by configuration - requesting credentials
04.01.2018 11:26:33.378 *INFO* [0:0:0:0:0:0:0:1 [1515083193376] GET /libs/granite/core/content/login.html HTTP/1.1] com.sample.project.core.filters.SampleServletFilter Calling Sample Servlet Filter
```
Tried with `service.ranking` property also, but it doesn't seems to be making a difference in AEM 6.2. 

Additional Information - We are not yet on AEM 6.3, but tried the [filter with modifications ](https://helpx.adobe.com/experience-manager/kt/platform-repository/using/osgi-http-whiteboard-code-sample-develop.html). Seems like the behavior is same as AEM 6.2.

Any pointers for this would help.

**Comment by davidjgonzalez** [comment]
@sandeepkumar03  updated the sample, can you try it out and let me know if it works for you? Thanks

https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/filters/impl/SampleServletFilter.java

**Comment by sandeepkumar03** [comment]
@davidjgonzalez Thanks for quick reply. Tried the filter with new http whiteboard annotations on AEM 6.2. The filter doesn't seem to be kicking in at all. Though can see that filter is registered.

`04.01.2018 14:24:17.597 *INFO* [qtp180434751-3459] com.sample.project.sampleproject.core Service [com.sample.project.core.filters.SampleServletFilter,5273, [javax.servlet.Filter]] ServiceEvent REGISTERED`

Accessed URL /content/samples/, don't see filter log, just the Sling authentication log

```
04.01.2018 14:27:16.530 *INFO* [qtp180434751-243] org.apache.sling.auth.core.impl.SlingAuthenticator getAnonymousResolver: Anonymous access not allowed by configuration - requesting credentials
04.01.2018 14:27:16.546 *WARN* [0:0:0:0:0:0:0:1 [1515094036542] GET /libs/granite/core/content/login.html HTTP/1.1] libs.granite.core.components.login.login$jsp j_reason param value 'unknown' cannot be mapped to a valid reason message: ignoring
```

One observation is, normally we see registered filters in http://host:port/system/console/status-httpwhiteboard. Don't see the filter there now. 

Additional Information - I am not using the full acs-aem-samples project as I was getting some bundle resolution error. So have copied just SampleServletFilter to a sample project and deployed that (but filter part is same, should not have issues with this ideally).

**Comment by davidjgonzalez** [comment]
@sandeepkumar03 do you have the regex OSGi property there as well? Try removing it and setting the pattern to /  ..

So you should have something like:
```
@Properties({
                    // A major difference from Sling Filters is Servlet Filters can be registered via the Felix HTTP Whiteboard to URL path patterns.

                    // A Pattern OR Regex must be provided.

                    // http://javadox.com/org.osgi/osgi.cmpn/6.0.0/org/osgi/service/http/whiteboard/HttpWhiteboardConstants.html#HTTP_WHITEBOARD_FILTER_PATTERN
                    @Property(name = HttpWhiteboardConstants.HTTP_WHITEBOARD_FILTER_PATTERN,
                                value = { "/" }),

                    // http://javadox.com/org.osgi/osgi.cmpn/6.0.0/org/osgi/service/http/whiteboard/HttpWhiteboardConstants.html#HTTP_WHITEBOARD_CONTEXT_SELECT
                    @Property(name = HttpWhiteboardConstants.HTTP_WHITEBOARD_CONTEXT_SELECT,
                                value = "(" + HttpWhiteboardConstants.HTTP_WHITEBOARD_CONTEXT_NAME + "=*)")
})
```

**Comment by sandeepkumar03** [comment]
@davidjgonzalez  Sorry didn't see the comment properly earlier. Making this change made some progress, but sequence of filter getting called is still later than Sling Engine.

Removed regex, added pattern to "/". Filter is getting called after sling authentication. Below are logs

```
04.01.2018 15:39:38.254 *INFO* [qtp180434751-3493] org.apache.sling.auth.core.impl.SlingAuthenticator getAnonymousResolver: Anonymous access not allowed by configuration - requesting credentials
04.01.2018 15:39:38.264 *INFO* [qtp180434751-3591] com.sample.project.core.filters.SampleServletFilter Calling Sample Servlet Filter
```

Some more information, http://host:port/system/console/status-httpservice console in AEM 6.2 shows filter information  (dispatcher: [REQUEST]), but there is no such information in AEM 6.1. Is it like http filter is behaving as [sling filter](https://sling.apache.org/documentation/the-sling-engine/filters.html#filter-processing) in AEM 6.2

```
Patterns : [/]
Name : com.sample.project.core.filters.SampleServletFilter
async : false
dispatcher : [REQUEST]
service.id : 5368
```

**Comment by sandeepkumar03** [comment]
@davidjgonzalez Raised a daycare ticket to investigate more on this. Below is the response from Adobe

> Apparently, this is the way AEM works now. The changes have been done to improve a security.

Seems like, we cannot bring Filter before Sling Authentication 6.2 onwards. If this information is enough to close the issue, we can close the issue. Meanwhile we would need to handle custom authentication in different manner 6.2 onwards.
 
Update -
Investigated more this on [sling auth source](https://github.com/apache/sling-org-apache-sling-auth-core/blob/master/src/main/java/org/apache/sling/auth/core/impl/SlingAuthenticator.java) is using HTTP Whiteboard method to register vs [sling auth source 1.3.6](https://github.com/apache/sling-org-apache-sling-auth-core/blob/org.apache.sling.auth.core-1.3.6/src/main/java/org/apache/sling/auth/core/impl/SlingAuthenticator.java). 1.3.6 is being used in AEM 6.1. That might be the reason.

**Comment by davidjgonzalez** [comment]
So there is now way to invoke a filter before sling auth is invoked? This is different than resource resolution right? Is this preventing you from doing a particular task?

**Comment by sandeepkumar03** [comment]
It seems that we cannot change order, may be I can try raising a issue in Sling Auth Core to check if order can be controlled.  This is different than sling resource resolution. 

Yes the execution order was preventing us to make our custom authentication work on AEM 6.2. But we did a AEM 6.2 specific workaround in Filter to handle the problematic scenario.

**Comment by davidjgonzalez** [comment]
@sandeepkumar03 any reason you are not using a Sling Authentication Handler to handle authentication? IDK what youre doing but seems like this is the natural hook.

Not sure if this [1] pattern would help you.

[1] https://github.com/Adobe-Consulting-Services/acs-aem-samples/blob/master/bundle/src/main/java/com/adobe/acs/samples/authentication/impl/SampleLoginHookAuthenticationHandler.java

**Comment by sandeepkumar03** [comment]
Thanks @davidjgonzalez for sample authentication handler. We have a authentication provider outside AEM, so flow is like

User request (not authenticated, redirects user to Login page of authentication provider) -> Login screen of authentication provider (set required cookies after authentication) -> Back to AEM, Filter validates and creates user on AEM, establishes session.

Probably we can look at custom Sling Authentication Handler also. We had SAML based authentication in one other project, where authentication provider was posting SAML response and was handled on AEM side to create user, establish session.

**Comment by davidjgonzalez** [comment]
Yeah - this sounds very much like the role of an authentication handler (or login module, but login modules are a bit of a pain so I tend to just use auth handlers)... sounds like you already have all the code so it seems like you’d just need to move it from the filter to the auth handler.

The saml use case might Warant looking at that hook example. That hook is derived from a use case where OOTB saml auth was used but upon successful auth, profile attributes has to be synced from sales force to aem, and the user had to also have their group membership shyster based on the sales force data.
